# ------------ DO NOT MODIFY: AUTO-GENERATED WITH python /opt/EntetelClient/PY/Relevad/prebid_all/relevad_prebid_maps.py --python -------------------
iab_codes2names_map = {
    "IAB1" : "Automotive",
    "IAB2-1" : "Automotive/Auto Body Styles",
    "IAB3-2" : "Automotive/Auto Body Styles/Commercial Trucks",
    "IAB8-2" : "Automotive/Auto Body Styles/Convertible",
    "IAB9-2" : "Automotive/Auto Body Styles/Coupe",
    "IAB10-2" : "Automotive/Auto Body Styles/Crossover",
    "IAB11-2" : "Automotive/Auto Body Styles/Hatchback",
    "IAB12-2" : "Automotive/Auto Body Styles/Microcar",
    "IAB13-2" : "Automotive/Auto Body Styles/Minivan",
    "IAB14-2" : "Automotive/Auto Body Styles/Off-Road Vehicles",
    "IAB15-2" : "Automotive/Auto Body Styles/Pickup Trucks",
    "IAB6-2" : "Automotive/Auto Body Styles/SUV",
    "IAB4-2" : "Automotive/Auto Body Styles/Sedan",
    "IAB5-2" : "Automotive/Auto Body Styles/Station Wagon",
    "IAB7-2" : "Automotive/Auto Body Styles/Van",
    "IAB30-1" : "Automotive/Auto Buying and Selling",
    "IAB31-1" : "Automotive/Auto Insurance",
    "IAB32-1" : "Automotive/Auto Parts",
    "IAB33-1" : "Automotive/Auto Recalls",
    "IAB41-1" : "Automotive/Auto Rentals",
    "IAB34-1" : "Automotive/Auto Repair",
    "IAB35-1" : "Automotive/Auto Safety",
    "IAB36-1" : "Automotive/Auto Shows",
    "IAB37-1" : "Automotive/Auto Technology",
    "IAB38-37" : "Automotive/Auto Technology/Auto Infotainment Technologies",
    "IAB39-37" : "Automotive/Auto Technology/Auto Navigation Systems",
    "IAB40-37" : "Automotive/Auto Technology/Auto Safety Technologies",
    "IAB16-1" : "Automotive/Auto Type",
    "IAB17-16" : "Automotive/Auto Type/Budget Cars",
    "IAB18-16" : "Automotive/Auto Type/Certified Pre-Owned Cars",
    "IAB19-16" : "Automotive/Auto Type/Classic Cars",
    "IAB20-16" : "Automotive/Auto Type/Concept Cars",
    "IAB21-16" : "Automotive/Auto Type/Driverless Cars",
    "IAB22-16" : "Automotive/Auto Type/Green Vehicles",
    "IAB23-16" : "Automotive/Auto Type/Luxury Cars",
    "IAB24-16" : "Automotive/Auto Type/Performance Cars",
    "IAB25-1" : "Automotive/Car Culture",
    "IAB26-1" : "Automotive/Dash Cam Videos",
    "IAB27-1" : "Automotive/Motorcycles",
    "IAB28-1" : "Automotive/Road-Side Assistance",
    "IAB29-1" : "Automotive/Scooters",
    "IAB42" : "Books and Literature",
    "IAB43-42" : "Books and Literature/Art and Photography Books",
    "IAB44-42" : "Books and Literature/Biographies",
    "IAB45-42" : "Books and Literature/Children's Literature",
    "IAB46-42" : "Books and Literature/Comics and Graphic Novels",
    "IAB47-42" : "Books and Literature/Cookbooks",
    "IAB48-42" : "Books and Literature/Fiction",
    "IAB49-42" : "Books and Literature/Poetry",
    "IAB50-42" : "Books and Literature/Travel Books",
    "IAB51-42" : "Books and Literature/Young Adult Literature",
    "IAB52" : "Business and Finance",
    "IAB53-52" : "Business and Finance/Business",
    "IAB54-53" : "Business and Finance/Business/Business Accounting & Finance",
    "IAB62-53" : "Business and Finance/Business/Business Administration",
    "IAB63-53" : "Business and Finance/Business/Business Banking & Finance",
    "IAB64-63" : "Business and Finance/Business/Business Banking & Finance/Angel Investment",
    "IAB65-63" : "Business and Finance/Business/Business Banking & Finance/Bankruptcy",
    "IAB66-63" : "Business and Finance/Business/Business Banking & Finance/Business Loans",
    "IAB67-63" : "Business and Finance/Business/Business Banking & Finance/Debt Factoring & Invoice Discounting",
    "IAB68-63" : "Business and Finance/Business/Business Banking & Finance/Mergers and Acquisitions",
    "IAB69-63" : "Business and Finance/Business/Business Banking & Finance/Private Equity",
    "IAB70-63" : "Business and Finance/Business/Business Banking & Finance/Sale & Lease Back",
    "IAB71-63" : "Business and Finance/Business/Business Banking & Finance/Venture Capital",
    "IAB72-53" : "Business and Finance/Business/Business I.T.",
    "IAB73-53" : "Business and Finance/Business/Business Operations",
    "IAB79-53" : "Business and Finance/Business/Business Utilities",
    "IAB74-53" : "Business and Finance/Business/Consumer Issues",
    "IAB75-74" : "Business and Finance/Business/Consumer Issues/Recalls",
    "IAB76-53" : "Business and Finance/Business/Executive Leadership & Management",
    "IAB77-53" : "Business and Finance/Business/Government Business",
    "IAB78-53" : "Business and Finance/Business/Green Solutions",
    "IAB55-53" : "Business and Finance/Business/Human Resources",
    "IAB56-53" : "Business and Finance/Business/Large Business",
    "IAB57-53" : "Business and Finance/Business/Logistics",
    "IAB58-53" : "Business and Finance/Business/Marketing and Advertising",
    "IAB59-53" : "Business and Finance/Business/Sales",
    "IAB60-53" : "Business and Finance/Business/Small and Medium-sized Business",
    "IAB61-53" : "Business and Finance/Business/Startups",
    "IAB80-52" : "Business and Finance/Economy",
    "IAB81-80" : "Business and Finance/Economy/Commodities",
    "IAB82-80" : "Business and Finance/Economy/Currencies",
    "IAB83-80" : "Business and Finance/Economy/Financial Crisis",
    "IAB84-80" : "Business and Finance/Economy/Financial Reform",
    "IAB85-80" : "Business and Finance/Economy/Financial Regulation",
    "IAB86-80" : "Business and Finance/Economy/Gasoline Prices",
    "IAB87-80" : "Business and Finance/Economy/Housing Market",
    "IAB88-80" : "Business and Finance/Economy/Interest Rates",
    "IAB89-80" : "Business and Finance/Economy/Job Market",
    "IAB90-52" : "Business and Finance/Industries",
    "IAB91-90" : "Business and Finance/Industries/Advertising Industry",
    "IAB102-90" : "Business and Finance/Industries/Agriculture",
    "IAB113-90" : "Business and Finance/Industries/Apparel Industry",
    "IAB117-90" : "Business and Finance/Industries/Automotive Industry",
    "IAB118-90" : "Business and Finance/Industries/Aviation Industry",
    "IAB119-90" : "Business and Finance/Industries/Biotech and Biomedical Industry",
    "IAB120-90" : "Business and Finance/Industries/Civil Engineering Industry",
    "IAB121-90" : "Business and Finance/Industries/Construction Industry",
    "IAB122-90" : "Business and Finance/Industries/Defense Industry",
    "IAB92-90" : "Business and Finance/Industries/Education industry",
    "IAB93-90" : "Business and Finance/Industries/Entertainment Industry",
    "IAB94-90" : "Business and Finance/Industries/Environmental Services Industry",
    "IAB95-90" : "Business and Finance/Industries/Financial Industry",
    "IAB96-90" : "Business and Finance/Industries/Food Industry",
    "IAB97-90" : "Business and Finance/Industries/Healthcare Industry",
    "IAB98-90" : "Business and Finance/Industries/Hospitality Industry",
    "IAB99-90" : "Business and Finance/Industries/Information Services Industry",
    "IAB100-90" : "Business and Finance/Industries/Legal Services Industry",
    "IAB101-90" : "Business and Finance/Industries/Logistics and Transportation Industry",
    "IAB103-90" : "Business and Finance/Industries/Management Consulting Industry",
    "IAB104-90" : "Business and Finance/Industries/Manufacturing Industry",
    "IAB105-90" : "Business and Finance/Industries/Mechanical and Industrial Engineering Industry",
    "IAB106-90" : "Business and Finance/Industries/Media Industry",
    "IAB107-90" : "Business and Finance/Industries/Metals Industry",
    "IAB108-90" : "Business and Finance/Industries/Non-Profit Organizations",
    "IAB109-90" : "Business and Finance/Industries/Pharmaceutical Industry",
    "IAB110-90" : "Business and Finance/Industries/Power and Energy Industry",
    "IAB111-90" : "Business and Finance/Industries/Publishing Industry",
    "IAB112-90" : "Business and Finance/Industries/Real Estate Industry",
    "IAB114-90" : "Business and Finance/Industries/Retail Industry",
    "IAB115-90" : "Business and Finance/Industries/Technology Industry",
    "IAB116-90" : "Business and Finance/Industries/Telecommunications Industry",
    "IAB123" : "Careers",
    "IAB124-123" : "Careers/Apprenticeships",
    "IAB125-123" : "Careers/Career Advice",
    "IAB126-123" : "Careers/Career Planning",
    "IAB127-123" : "Careers/Job Search",
    "IAB128-127" : "Careers/Job Search/Job Fairs",
    "IAB129-127" : "Careers/Job Search/Resume Writing and Advice",
    "IAB130-123" : "Careers/Remote Working",
    "IAB131-123" : "Careers/Vocational Training",
    "IAB132" : "Education",
    "IAB133-132" : "Education/Adult Education",
    "IAB137-132" : "Education/College Education",
    "IAB138-137" : "Education/College Education/College Planning",
    "IAB139-137" : "Education/College Education/Postgraduate Education",
    "IAB140-139" : "Education/College Education/Postgraduate Education/Professional School",
    "IAB141-137" : "Education/College Education/Undergraduate Education",
    "IAB142-132" : "Education/Early Childhood Education",
    "IAB143-132" : "Education/Educational Assessment",
    "IAB144-143" : "Education/Educational Assessment/Standardized Testing",
    "IAB145-132" : "Education/Homeschooling",
    "IAB146-132" : "Education/Homework and Study",
    "IAB147-132" : "Education/Language Learning",
    "IAB148-132" : "Education/Online Education",
    "IAB149-132" : "Education/Primary Education",
    "IAB134-132" : "Education/Private School",
    "IAB135-132" : "Education/Secondary Education",
    "IAB136-132" : "Education/Special Education",
    "IAB150" : "Events and Attractions",
    "IAB151-150" : "Events and Attractions/Amusement and Theme Parks",
    "IAB162-150" : "Events and Attractions/Awards Shows",
    "IAB179-150" : "Events and Attractions/Bars & Restaurants",
    "IAB180-150" : "Events and Attractions/Business Expos & Conferences",
    "IAB181-150" : "Events and Attractions/Casinos & Gambling",
    "IAB182-150" : "Events and Attractions/Cinemas and Events",
    "IAB183-150" : "Events and Attractions/Comedy Events",
    "IAB184-150" : "Events and Attractions/Concerts & Music Events",
    "IAB185-150" : "Events and Attractions/Fan Conventions",
    "IAB152-150" : "Events and Attractions/Fashion Events",
    "IAB153-150" : "Events and Attractions/Historic Site and Landmark Tours",
    "IAB154-150" : "Events and Attractions/Malls & Shopping Centers",
    "IAB155-150" : "Events and Attractions/Museums & Galleries",
    "IAB156-150" : "Events and Attractions/Musicals",
    "IAB157-150" : "Events and Attractions/National & Civic Holidays",
    "IAB158-150" : "Events and Attractions/Nightclubs",
    "IAB159-150" : "Events and Attractions/Outdoor Activities",
    "IAB160-150" : "Events and Attractions/Parks & Nature",
    "IAB161-150" : "Events and Attractions/Party Supplies and Decorations",
    "IAB163-150" : "Events and Attractions/Personal Celebrations & Life Events",
    "IAB164-163" : "Events and Attractions/Personal Celebrations & Life Events/Anniversary",
    "IAB166-163" : "Events and Attractions/Personal Celebrations & Life Events/Baby Shower",
    "IAB167-163" : "Events and Attractions/Personal Celebrations & Life Events/Bachelor Party",
    "IAB168-163" : "Events and Attractions/Personal Celebrations & Life Events/Bachelorette Party",
    "IAB169-163" : "Events and Attractions/Personal Celebrations & Life Events/Birth",
    "IAB170-163" : "Events and Attractions/Personal Celebrations & Life Events/Birthday",
    "IAB171-163" : "Events and Attractions/Personal Celebrations & Life Events/Funeral",
    "IAB172-163" : "Events and Attractions/Personal Celebrations & Life Events/Graduation",
    "IAB173-163" : "Events and Attractions/Personal Celebrations & Life Events/Prom",
    "IAB165-163" : "Events and Attractions/Personal Celebrations & Life Events/Wedding",
    "IAB174-150" : "Events and Attractions/Political Event",
    "IAB175-150" : "Events and Attractions/Religious Events",
    "IAB176-150" : "Events and Attractions/Sporting Events",
    "IAB177-150" : "Events and Attractions/Theater Venues and Events",
    "IAB178-150" : "Events and Attractions/Zoos & Aquariums",
    "IAB186" : "Family and Relationships",
    "IAB187-186" : "Family and Relationships/Bereavement",
    "IAB188-186" : "Family and Relationships/Dating",
    "IAB189-186" : "Family and Relationships/Divorce",
    "IAB190-186" : "Family and Relationships/Eldercare",
    "IAB191-186" : "Family and Relationships/Marriage and Civil Unions",
    "IAB192-186" : "Family and Relationships/Parenting",
    "IAB193-192" : "Family and Relationships/Parenting/Adoption and Fostering",
    "IAB194-192" : "Family and Relationships/Parenting/Daycare and Pre-School",
    "IAB195-192" : "Family and Relationships/Parenting/Internet Safety",
    "IAB196-192" : "Family and Relationships/Parenting/Parenting Babies and Toddlers",
    "IAB197-192" : "Family and Relationships/Parenting/Parenting Children Aged 4-11",
    "IAB198-192" : "Family and Relationships/Parenting/Parenting Teens",
    "IAB199-192" : "Family and Relationships/Parenting/Special Needs Kids",
    "IAB200-186" : "Family and Relationships/Single Life",
    "IAB201" : "Fine Art",
    "IAB202-201" : "Fine Art/Costume",
    "IAB203-201" : "Fine Art/Dance",
    "IAB204-201" : "Fine Art/Design",
    "IAB205-201" : "Fine Art/Digital Arts",
    "IAB206-201" : "Fine Art/Fine Art Photography",
    "IAB207-201" : "Fine Art/Modern Art",
    "IAB208-201" : "Fine Art/Opera",
    "IAB209-201" : "Fine Art/Theater",
    "IAB210" : "Food & Drink",
    "IAB211-210" : "Food & Drink/Alcoholic Beverages",
    "IAB215-210" : "Food & Drink/Barbecues and Grilling",
    "IAB216-210" : "Food & Drink/Cooking",
    "IAB217-210" : "Food & Drink/Desserts and Baking",
    "IAB218-210" : "Food & Drink/Dining Out",
    "IAB219-210" : "Food & Drink/Food Allergies",
    "IAB220-210" : "Food & Drink/Food Movements",
    "IAB221-210" : "Food & Drink/Healthy Cooking and Eating",
    "IAB222-210" : "Food & Drink/Non-Alcoholic Beverages",
    "IAB212-210" : "Food & Drink/Vegan Diets",
    "IAB213-210" : "Food & Drink/Vegetarian Diets",
    "IAB214-210" : "Food & Drink/World Cuisines",
    "IAB323-286" : "Health/Cosmetic Medical Services",
    "IAB287-286" : "Health/Diseases and Conditions",
    "IAB288-287" : "Health/Diseases and Conditions/Allergies",
    "IAB306-287" : "Health/Diseases and Conditions/Blood Disorders",
    "IAB312-287" : "Health/Diseases and Conditions/Bone and Joint Conditions",
    "IAB313-287" : "Health/Diseases and Conditions/Brain and Nervous System Disorders",
    "IAB314-287" : "Health/Diseases and Conditions/Cancer",
    "IAB315-287" : "Health/Diseases and Conditions/Cold and Flu",
    "IAB316-287" : "Health/Diseases and Conditions/Dental Health",
    "IAB317-287" : "Health/Diseases and Conditions/Diabetes",
    "IAB318-287" : "Health/Diseases and Conditions/Digestive Disorders",
    "IAB289-287" : "Health/Diseases and Conditions/Ear, Nose and Throat Conditions",
    "IAB290-287" : "Health/Diseases and Conditions/Endocrine and Metabolic Diseases",
    "IAB291-290" : "Health/Diseases and Conditions/Endocrine and Metabolic Diseases/Hormonal Disorders",
    "IAB292-290" : "Health/Diseases and Conditions/Endocrine and Metabolic Diseases/Menopause",
    "IAB293-290" : "Health/Diseases and Conditions/Endocrine and Metabolic Diseases/Thyroid Disorders",
    "IAB294-287" : "Health/Diseases and Conditions/Eye and Vision Conditions",
    "IAB295-287" : "Health/Diseases and Conditions/Foot Health",
    "IAB296-287" : "Health/Diseases and Conditions/Heart and Cardiovascular Diseases",
    "IAB297-287" : "Health/Diseases and Conditions/Infectious Diseases",
    "IAB298-287" : "Health/Diseases and Conditions/Injuries",
    "IAB299-298" : "Health/Diseases and Conditions/Injuries/First Aid",
    "IAB300-287" : "Health/Diseases and Conditions/Lung and Respiratory Health",
    "IAB301-287" : "Health/Diseases and Conditions/Mental Health",
    "IAB302-287" : "Health/Diseases and Conditions/Reproductive Health",
    "IAB303-302" : "Health/Diseases and Conditions/Reproductive Health/Birth Control",
    "IAB304-302" : "Health/Diseases and Conditions/Reproductive Health/Infertility",
    "IAB305-302" : "Health/Diseases and Conditions/Reproductive Health/Pregnancy",
    "IAB307-287" : "Health/Diseases and Conditions/Sexual Health",
    "IAB308-307" : "Health/Diseases and Conditions/Sexual Health/Sexual Conditions",
    "IAB309-287" : "Health/Diseases and Conditions/Skin and Dermatology",
    "IAB310-287" : "Health/Diseases and Conditions/Sleep Disorders",
    "IAB311-287" : "Health/Diseases and Conditions/Substance Abuse",
    "IAB319-286" : "Health/Medical Tests",
    "IAB320-286" : "Health/Pharmaceutical Drugs",
    "IAB321-286" : "Health/Surgery",
    "IAB322-286" : "Health/Vaccines",
    "IAB223" : "Healthy Living",
    "IAB224-223" : "Healthy Living/Children's Health",
    "IAB225-223" : "Healthy Living/Fitness and Exercise",
    "IAB226-225" : "Healthy Living/Fitness and Exercise/Participant Sports",
    "IAB227-225" : "Healthy Living/Fitness and Exercise/Running and Jogging",
    "IAB228-223" : "Healthy Living/Men's Health",
    "IAB229-223" : "Healthy Living/Nutrition",
    "IAB230-223" : "Healthy Living/Senior Health",
    "IAB231-223" : "Healthy Living/Weight Loss",
    "IAB232-223" : "Healthy Living/Wellness",
    "IAB233-232" : "Healthy Living/Wellness/Alternative Medicine",
    "IAB234-233" : "Healthy Living/Wellness/Alternative Medicine/Herbs and Supplements",
    "IAB235-233" : "Healthy Living/Wellness/Alternative Medicine/Holistic Health",
    "IAB236-232" : "Healthy Living/Wellness/Physical Therapy",
    "IAB237-232" : "Healthy Living/Wellness/Smoking Cessation",
    "IAB238-223" : "Healthy Living/Women's Health",
    "IAB239" : "Hobbies & Interests",
    "IAB240-239" : "Hobbies & Interests/Antiquing and Antiques",
    "IAB248-239" : "Hobbies & Interests/Arts and Crafts",
    "IAB249-248" : "Hobbies & Interests/Arts and Crafts/Beadwork",
    "IAB250-248" : "Hobbies & Interests/Arts and Crafts/Candle and Soap Making",
    "IAB251-248" : "Hobbies & Interests/Arts and Crafts/Drawing and Sketching",
    "IAB252-248" : "Hobbies & Interests/Arts and Crafts/Jewelry Making",
    "IAB253-248" : "Hobbies & Interests/Arts and Crafts/Needlework",
    "IAB254-248" : "Hobbies & Interests/Arts and Crafts/Painting",
    "IAB255-248" : "Hobbies & Interests/Arts and Crafts/Photography",
    "IAB256-248" : "Hobbies & Interests/Arts and Crafts/Scrapbooking",
    "IAB257-248" : "Hobbies & Interests/Arts and Crafts/Woodworking",
    "IAB258-239" : "Hobbies & Interests/Beekeeping",
    "IAB259-239" : "Hobbies & Interests/Birdwatching",
    "IAB260-239" : "Hobbies & Interests/Cigars",
    "IAB261-239" : "Hobbies & Interests/Collecting",
    "IAB262-261" : "Hobbies & Interests/Collecting/Comic Books",
    "IAB263-261" : "Hobbies & Interests/Collecting/Stamps and Coins",
    "IAB269-239" : "Hobbies & Interests/Games and Puzzles",
    "IAB270-269" : "Hobbies & Interests/Games and Puzzles/Board Games and Puzzles",
    "IAB271-269" : "Hobbies & Interests/Games and Puzzles/Card Games",
    "IAB272-269" : "Hobbies & Interests/Games and Puzzles/Roleplaying Games",
    "IAB273-239" : "Hobbies & Interests/Genealogy and Ancestry",
    "IAB241-239" : "Hobbies & Interests/Magic and Illusion",
    "IAB242-239" : "Hobbies & Interests/Model Toys",
    "IAB243-239" : "Hobbies & Interests/Musical Instruments",
    "IAB244-239" : "Hobbies & Interests/Paranormal Phenomena",
    "IAB245-239" : "Hobbies & Interests/Radio Control",
    "IAB246-239" : "Hobbies & Interests/Sci-fi and Fantasy",
    "IAB247-239" : "Hobbies & Interests/Workshops and Classes",
    "IAB274" : "Home & Garden",
    "IAB275-274" : "Home & Garden/Gardening",
    "IAB278-274" : "Home & Garden/Home Appliances",
    "IAB279-274" : "Home & Garden/Home Entertaining",
    "IAB280-274" : "Home & Garden/Home Improvement",
    "IAB281-274" : "Home & Garden/Home Security",
    "IAB282-274" : "Home & Garden/Indoor Environmental Quality",
    "IAB283-274" : "Home & Garden/Interior Decorating",
    "IAB284-274" : "Home & Garden/Landscaping",
    "IAB285-274" : "Home & Garden/Outdoor Decorating",
    "IAB276-274" : "Home & Garden/Remodeling & Construction",
    "IAB277-274" : "Home & Garden/Smart Home",
    "IAB286" : "Medical Health",
    "IAB323-286" : "Medical Health/Cosmetic Medical Services",
    "IAB287-286" : "Medical Health/Diseases and Conditions",
    "IAB288-287" : "Medical Health/Diseases and Conditions/Allergies",
    "IAB306-287" : "Medical Health/Diseases and Conditions/Blood Disorders",
    "IAB312-287" : "Medical Health/Diseases and Conditions/Bone and Joint Conditions",
    "IAB313-287" : "Medical Health/Diseases and Conditions/Brain and Nervous System Disorders",
    "IAB314-287" : "Medical Health/Diseases and Conditions/Cancer",
    "IAB315-287" : "Medical Health/Diseases and Conditions/Cold and Flu",
    "IAB316-287" : "Medical Health/Diseases and Conditions/Dental Health",
    "IAB317-287" : "Medical Health/Diseases and Conditions/Diabetes",
    "IAB318-287" : "Medical Health/Diseases and Conditions/Digestive Disorders",
    "IAB289-287" : "Medical Health/Diseases and Conditions/Ear, Nose and Throat Conditions",
    "IAB290-287" : "Medical Health/Diseases and Conditions/Endocrine and Metabolic Diseases",
    "IAB291-290" : "Medical Health/Diseases and Conditions/Endocrine and Metabolic Diseases/Hormonal Disorders",
    "IAB292-290" : "Medical Health/Diseases and Conditions/Endocrine and Metabolic Diseases/Menopause",
    "IAB293-290" : "Medical Health/Diseases and Conditions/Endocrine and Metabolic Diseases/Thyroid Disorders",
    "IAB294-287" : "Medical Health/Diseases and Conditions/Eye and Vision Conditions",
    "IAB295-287" : "Medical Health/Diseases and Conditions/Foot Health",
    "IAB296-287" : "Medical Health/Diseases and Conditions/Heart and Cardiovascular Diseases",
    "IAB297-287" : "Medical Health/Diseases and Conditions/Infectious Diseases",
    "IAB298-287" : "Medical Health/Diseases and Conditions/Injuries",
    "IAB299-298" : "Medical Health/Diseases and Conditions/Injuries/First Aid",
    "IAB300-287" : "Medical Health/Diseases and Conditions/Lung and Respiratory Health",
    "IAB301-287" : "Medical Health/Diseases and Conditions/Mental Health",
    "IAB302-287" : "Medical Health/Diseases and Conditions/Reproductive Health",
    "IAB303-302" : "Medical Health/Diseases and Conditions/Reproductive Health/Birth Control",
    "IAB304-302" : "Medical Health/Diseases and Conditions/Reproductive Health/Infertility",
    "IAB305-302" : "Medical Health/Diseases and Conditions/Reproductive Health/Pregnancy",
    "IAB307-287" : "Medical Health/Diseases and Conditions/Sexual Health",
    "IAB308-307" : "Medical Health/Diseases and Conditions/Sexual Health/Sexual Conditions",
    "IAB309-287" : "Medical Health/Diseases and Conditions/Skin and Dermatology",
    "IAB310-287" : "Medical Health/Diseases and Conditions/Sleep Disorders",
    "IAB311-287" : "Medical Health/Diseases and Conditions/Substance Abuse",
    "IAB319-286" : "Medical Health/Medical Tests",
    "IAB320-286" : "Medical Health/Pharmaceutical Drugs",
    "IAB321-286" : "Medical Health/Surgery",
    "IAB322-286" : "Medical Health/Vaccines",
    "IAB324" : "Movies",
    "IAB325-324" : "Movies/Action and Adventure Movies",
    "IAB329-324" : "Movies/Animation Movies",
    "IAB330-324" : "Movies/Comedy Movies",
    "IAB331-324" : "Movies/Crime and Mystery Movies",
    "IAB332-324" : "Movies/Documentary Movies",
    "IAB333-324" : "Movies/Drama Movies",
    "IAB334-324" : "Movies/Family and Children Movies",
    "IAB335-324" : "Movies/Fantasy Movies",
    "IAB336-324" : "Movies/Horror Movies",
    "IAB328-324" : "Movies/Indie and Arthouse Movies",
    "IAB326-324" : "Movies/Romance Movies",
    "IAB327-324" : "Movies/Science Fiction Movies",
    "IAB337-324" : "Movies/World Movies",
    "IAB338" : "Music and Audio",
    "IAB342-338" : "Music and Audio/Adult Album Alternative",
    "IAB339-338" : "Music and Audio/Adult Contemporary Music",
    "IAB340-339" : "Music and Audio/Adult Contemporary Music/Soft AC Music",
    "IAB341-339" : "Music and Audio/Adult Contemporary Music/Urban AC Music",
    "IAB343-338" : "Music and Audio/Alternative Music",
    "IAB360-338" : "Music and Audio/Blues",
    "IAB344-338" : "Music and Audio/Children's Music",
    "IAB345-338" : "Music and Audio/Classic Hits",
    "IAB346-338" : "Music and Audio/Classical Music",
    "IAB347-338" : "Music and Audio/College Radio",
    "IAB348-338" : "Music and Audio/Comedy (Music and Audio)",
    "IAB349-338" : "Music and Audio/Contemporary Hits/Pop/Top 40",
    "IAB350-338" : "Music and Audio/Country Music",
    "IAB351-338" : "Music and Audio/Dance and Electronic Music",
    "IAB354-338" : "Music and Audio/Gospel Music",
    "IAB355-338" : "Music and Audio/Hip Hop Music",
    "IAB356-338" : "Music and Audio/Inspirational/New Age Music",
    "IAB357-338" : "Music and Audio/Jazz",
    "IAB358-338" : "Music and Audio/Oldies/Adult Standards",
    "IAB362-338" : "Music and Audio/R&B/Soul/Funk",
    "IAB359-338" : "Music and Audio/Reggae",
    "IAB361-338" : "Music and Audio/Religious (Music and Audio)",
    "IAB363-338" : "Music and Audio/Rock Music",
    "IAB364-363" : "Music and Audio/Rock Music/Album-oriented Rock",
    "IAB365-363" : "Music and Audio/Rock Music/Alternative Rock",
    "IAB366-363" : "Music and Audio/Rock Music/Classic Rock",
    "IAB367-363" : "Music and Audio/Rock Music/Hard Rock",
    "IAB368-363" : "Music and Audio/Rock Music/Soft Rock",
    "IAB353-338" : "Music and Audio/Songwriters/Folk",
    "IAB369-338" : "Music and Audio/Soundtracks, TV and Showtunes",
    "IAB370-338" : "Music and Audio/Sports Radio",
    "IAB371-338" : "Music and Audio/Talk Radio",
    "IAB372-371" : "Music and Audio/Talk Radio/Business News Radio",
    "IAB373-371" : "Music and Audio/Talk Radio/Educational Radio",
    "IAB374-371" : "Music and Audio/Talk Radio/News Radio",
    "IAB375-371" : "Music and Audio/Talk Radio/News/Talk Radio",
    "IAB376-371" : "Music and Audio/Talk Radio/Public Radio",
    "IAB377-338" : "Music and Audio/Urban Contemporary Music",
    "IAB378-338" : "Music and Audio/Variety (Music and Audio)",
    "IAB352-338" : "Music and Audio/World/International Music",
    "IAB379" : "News and Politics",
    "IAB380-379" : "News and Politics/Crime",
    "IAB381-379" : "News and Politics/Disasters",
    "IAB382-379" : "News and Politics/International News",
    "IAB383-379" : "News and Politics/Law",
    "IAB384-379" : "News and Politics/Local News",
    "IAB385-379" : "News and Politics/National News",
    "IAB386-379" : "News and Politics/Politics",
    "IAB387-386" : "News and Politics/Politics/Elections",
    "IAB388-386" : "News and Politics/Politics/Political Issues",
    "IAB389-386" : "News and Politics/Politics/War and Conflicts",
    "IAB390-379" : "News and Politics/Weather",
    "IAB391" : "Personal Finance",
    "IAB392-391" : "Personal Finance/Consumer Banking",
    "IAB393-391" : "Personal Finance/Financial Assistance",
    "IAB394-393" : "Personal Finance/Financial Assistance/Government Support and Welfare",
    "IAB395-393" : "Personal Finance/Financial Assistance/Student Financial Aid",
    "IAB396-391" : "Personal Finance/Financial Planning",
    "IAB397-391" : "Personal Finance/Frugal Living",
    "IAB417-391" : "Personal Finance/Home Utilities",
    "IAB418-417" : "Personal Finance/Home Utilities/Gas and Electric",
    "IAB419-417" : "Personal Finance/Home Utilities/Internet Service Providers",
    "IAB420-417" : "Personal Finance/Home Utilities/Phone Services",
    "IAB421-417" : "Personal Finance/Home Utilities/Water Services",
    "IAB398-391" : "Personal Finance/Insurance",
    "IAB399-398" : "Personal Finance/Insurance/Health Insurance",
    "IAB400-398" : "Personal Finance/Insurance/Home Insurance",
    "IAB401-398" : "Personal Finance/Insurance/Life Insurance",
    "IAB402-398" : "Personal Finance/Insurance/Motor Insurance",
    "IAB403-398" : "Personal Finance/Insurance/Pet Insurance",
    "IAB404-398" : "Personal Finance/Insurance/Travel Insurance",
    "IAB405-391" : "Personal Finance/Personal Debt",
    "IAB406-405" : "Personal Finance/Personal Debt/Credit Cards",
    "IAB407-405" : "Personal Finance/Personal Debt/Home Financing",
    "IAB408-405" : "Personal Finance/Personal Debt/Personal Loans",
    "IAB409-405" : "Personal Finance/Personal Debt/Student Loans",
    "IAB410-391" : "Personal Finance/Personal Investing",
    "IAB411-410" : "Personal Finance/Personal Investing/Hedge Funds",
    "IAB412-410" : "Personal Finance/Personal Investing/Mutual Funds",
    "IAB413-410" : "Personal Finance/Personal Investing/Options",
    "IAB414-410" : "Personal Finance/Personal Investing/Stocks and Bonds",
    "IAB415-391" : "Personal Finance/Personal Taxes",
    "IAB416-391" : "Personal Finance/Retirement Planning",
    "IAB422" : "Pets",
    "IAB423-422" : "Pets/Birds",
    "IAB424-422" : "Pets/Cats",
    "IAB425-422" : "Pets/Dogs",
    "IAB426-422" : "Pets/Fish and Aquariums",
    "IAB427-422" : "Pets/Large Animals",
    "IAB428-422" : "Pets/Pet Adoptions",
    "IAB431-422" : "Pets/Pet Supplies",
    "IAB429-422" : "Pets/Reptiles",
    "IAB430-422" : "Pets/Veterinary Medicine",
    "IAB432" : "Pop Culture",
    "IAB433-432" : "Pop Culture/Celebrity Deaths",
    "IAB434-432" : "Pop Culture/Celebrity Families",
    "IAB435-432" : "Pop Culture/Celebrity Homes",
    "IAB436-432" : "Pop Culture/Celebrity Pregnancy",
    "IAB437-432" : "Pop Culture/Celebrity Relationships",
    "IAB438-432" : "Pop Culture/Celebrity Scandal",
    "IAB439-432" : "Pop Culture/Celebrity Style",
    "IAB440-432" : "Pop Culture/Humor and Satire",
    "IAB441" : "Real Estate",
    "IAB442-441" : "Real Estate/Apartments",
    "IAB445-441" : "Real Estate/Developmental Sites",
    "IAB446-441" : "Real Estate/Hotel Properties",
    "IAB447-441" : "Real Estate/Houses",
    "IAB448-441" : "Real Estate/Industrial Property",
    "IAB449-441" : "Real Estate/Land and Farms",
    "IAB450-441" : "Real Estate/Office Property",
    "IAB451-441" : "Real Estate/Real Estate Buying and Selling",
    "IAB452-441" : "Real Estate/Real Estate Renting and Leasing",
    "IAB443-441" : "Real Estate/Retail Property",
    "IAB444-441" : "Real Estate/Vacation Properties",
    "IAB453" : "Religion & Spirituality",
    "IAB454-453" : "Religion & Spirituality/Agnosticism",
    "IAB456-453" : "Religion & Spirituality/Astrology",
    "IAB457-453" : "Religion & Spirituality/Atheism",
    "IAB458-453" : "Religion & Spirituality/Buddhism",
    "IAB459-453" : "Religion & Spirituality/Christianity",
    "IAB460-453" : "Religion & Spirituality/Hinduism",
    "IAB461-453" : "Religion & Spirituality/Islam",
    "IAB462-453" : "Religion & Spirituality/Judaism",
    "IAB463-453" : "Religion & Spirituality/Sikhism",
    "IAB455-453" : "Religion & Spirituality/Spirituality",
    "IAB464" : "Science",
    "IAB465-464" : "Science/Biological Sciences",
    "IAB466-464" : "Science/Chemistry",
    "IAB467-464" : "Science/Environment",
    "IAB468-464" : "Science/Genetics",
    "IAB469-464" : "Science/Geography",
    "IAB470-464" : "Science/Geology",
    "IAB471-464" : "Science/Physics",
    "IAB472-464" : "Science/Space and Astronomy",
    "IAB473" : "Shopping",
    "IAB482-473" : "Shopping/Children's Games and Toys",
    "IAB474-473" : "Shopping/Coupons and Discounts",
    "IAB475-473" : "Shopping/Flower Shopping",
    "IAB476-473" : "Shopping/Gifts and Greetings Cards",
    "IAB477-473" : "Shopping/Grocery Shopping",
    "IAB478-473" : "Shopping/Holiday Shopping",
    "IAB479-473" : "Shopping/Household Supplies",
    "IAB480-473" : "Shopping/Lotteries and Scratchcards",
    "IAB481-473" : "Shopping/Sales and Promotions",
    "IAB483" : "Sports",
    "IAB484-483" : "Sports/American Football",
    "IAB507-483" : "Sports/Australian Rules Football",
    "IAB518-483" : "Sports/Auto Racing",
    "IAB519-518" : "Sports/Auto Racing/Motorcycle Sports",
    "IAB534-483" : "Sports/Badminton",
    "IAB545-483" : "Sports/Baseball",
    "IAB547-483" : "Sports/Basketball",
    "IAB548-483" : "Sports/Beach Volleyball",
    "IAB549-483" : "Sports/Bodybuilding",
    "IAB550-483" : "Sports/Bowling",
    "IAB485-483" : "Sports/Boxing",
    "IAB486-483" : "Sports/Cheerleading",
    "IAB487-483" : "Sports/College Sports",
    "IAB490-487" : "Sports/College Sports/College Baseball",
    "IAB489-487" : "Sports/College Sports/College Basketball",
    "IAB488-487" : "Sports/College Sports/College Football",
    "IAB491-483" : "Sports/Cricket",
    "IAB492-483" : "Sports/Cycling",
    "IAB493-483" : "Sports/Darts",
    "IAB494-483" : "Sports/Disabled Sports",
    "IAB495-483" : "Sports/Diving",
    "IAB496-483" : "Sports/Equine Sports",
    "IAB497-483" : "Sports/Equine Sports/Horse Racing",
    "IAB498-483" : "Sports/Extreme Sports",
    "IAB499-498" : "Sports/Extreme Sports/Canoeing and Kayaking",
    "IAB500-498" : "Sports/Extreme Sports/Climbing",
    "IAB501-498" : "Sports/Extreme Sports/Paintball",
    "IAB502-498" : "Sports/Extreme Sports/Scuba Diving",
    "IAB503-498" : "Sports/Extreme Sports/Skateboarding",
    "IAB504-498" : "Sports/Extreme Sports/Snowboarding",
    "IAB505-498" : "Sports/Extreme Sports/Surfing and Bodyboarding",
    "IAB506-498" : "Sports/Extreme Sports/Waterskiing and Wakeboarding",
    "IAB508-483" : "Sports/Fantasy Sports",
    "IAB509-483" : "Sports/Field Hockey",
    "IAB510-483" : "Sports/Figure Skating",
    "IAB511-483" : "Sports/Fishing Sports",
    "IAB512-483" : "Sports/Golf",
    "IAB513-483" : "Sports/Gymnastics",
    "IAB514-483" : "Sports/Hunting and Shooting",
    "IAB515-483" : "Sports/Ice Hockey",
    "IAB516-483" : "Sports/Inline Skating",
    "IAB517-483" : "Sports/Lacrosse",
    "IAB520-483" : "Sports/Martial Arts",
    "IAB521-483" : "Sports/Olympic Sports",
    "IAB522-521" : "Sports/Olympic Sports/Summer Olympic Sports",
    "IAB523-521" : "Sports/Olympic Sports/Winter Olympic Sports",
    "IAB524-483" : "Sports/Poker and Professional Gambling",
    "IAB525-483" : "Sports/Rodeo",
    "IAB526-483" : "Sports/Rowing",
    "IAB527-483" : "Sports/Rugby",
    "IAB528-527" : "Sports/Rugby/Rugby League",
    "IAB529-527" : "Sports/Rugby/Rugby Union",
    "IAB530-483" : "Sports/Sailing",
    "IAB531-483" : "Sports/Skiing",
    "IAB532-483" : "Sports/Snooker/Pool/Billiards",
    "IAB533-483" : "Sports/Soccer",
    "IAB535-483" : "Sports/Softball",
    "IAB551-483" : "Sports/Sports Equipment",
    "IAB536-483" : "Sports/Squash",
    "IAB537-483" : "Sports/Swimming",
    "IAB538-483" : "Sports/Table Tennis",
    "IAB539-483" : "Sports/Tennis",
    "IAB540-483" : "Sports/Track and Field",
    "IAB541-483" : "Sports/Volleyball",
    "IAB542-483" : "Sports/Walking",
    "IAB543-483" : "Sports/Water Polo",
    "IAB544-483" : "Sports/Weightlifting",
    "IAB546-483" : "Sports/Wrestling",
    "IAB552" : "Style & Fashion",
    "IAB553-552" : "Style & Fashion/Beauty",
    "IAB554-553" : "Style & Fashion/Beauty/Hair Care",
    "IAB555-553" : "Style & Fashion/Beauty/Makeup and Accessories",
    "IAB556-553" : "Style & Fashion/Beauty/Nail Care",
    "IAB557-553" : "Style & Fashion/Beauty/Natural and Organic Beauty",
    "IAB558-553" : "Style & Fashion/Beauty/Perfume and Fragrance",
    "IAB559-553" : "Style & Fashion/Beauty/Skin Care",
    "IAB574-552" : "Style & Fashion/Body Art",
    "IAB575-552" : "Style & Fashion/Children's Clothing",
    "IAB576-552" : "Style & Fashion/Designer Clothing",
    "IAB577-552" : "Style & Fashion/Fashion Trends",
    "IAB578-552" : "Style & Fashion/High Fashion",
    "IAB579-552" : "Style & Fashion/Men's Fashion",
    "IAB580-579" : "Style & Fashion/Men's Fashion/Men's Accessories",
    "IAB581-580" : "Style & Fashion/Men's Fashion/Men's Accessories/Men's Jewelry and Watches",
    "IAB582-579" : "Style & Fashion/Men's Fashion/Men's Clothing",
    "IAB583-582" : "Style & Fashion/Men's Fashion/Men's Clothing/Men's Business Wear",
    "IAB584-582" : "Style & Fashion/Men's Fashion/Men's Clothing/Men's Casual Wear",
    "IAB585-582" : "Style & Fashion/Men's Fashion/Men's Clothing/Men's Formal Wear",
    "IAB586-582" : "Style & Fashion/Men's Fashion/Men's Clothing/Men's Outerwear",
    "IAB587-582" : "Style & Fashion/Men's Fashion/Men's Clothing/Men's Sportswear",
    "IAB588-582" : "Style & Fashion/Men's Fashion/Men's Clothing/Men's Underwear and Sleepwear",
    "IAB589-579" : "Style & Fashion/Men's Fashion/Men's Shoes and Footwear",
    "IAB590-552" : "Style & Fashion/Personal Care",
    "IAB591-590" : "Style & Fashion/Personal Care/Bath and Shower",
    "IAB592-590" : "Style & Fashion/Personal Care/Deodorant and Antiperspirant",
    "IAB593-590" : "Style & Fashion/Personal Care/Oral care",
    "IAB594-590" : "Style & Fashion/Personal Care/Shaving",
    "IAB595-552" : "Style & Fashion/Street Style",
    "IAB560-552" : "Style & Fashion/Women's Fashion",
    "IAB561-560" : "Style & Fashion/Women's Fashion/Women's Accessories",
    "IAB562-561" : "Style & Fashion/Women's Fashion/Women's Accessories/Women's Glasses",
    "IAB563-561" : "Style & Fashion/Women's Fashion/Women's Accessories/Women's Handbags and Wallets",
    "IAB564-561" : "Style & Fashion/Women's Fashion/Women's Accessories/Women's Hats and Scarves",
    "IAB565-561" : "Style & Fashion/Women's Fashion/Women's Accessories/Women's Jewelry and Watches",
    "IAB566-560" : "Style & Fashion/Women's Fashion/Women's Clothing",
    "IAB567-566" : "Style & Fashion/Women's Fashion/Women's Clothing/Women's Business Wear",
    "IAB568-566" : "Style & Fashion/Women's Fashion/Women's Clothing/Women's Casual Wear",
    "IAB569-566" : "Style & Fashion/Women's Fashion/Women's Clothing/Women's Formal Wear",
    "IAB570-566" : "Style & Fashion/Women's Fashion/Women's Clothing/Women's Intimates and Sleepwear",
    "IAB571-566" : "Style & Fashion/Women's Fashion/Women's Clothing/Women's Outerwear",
    "IAB572-566" : "Style & Fashion/Women's Fashion/Women's Clothing/Women's Sportswear",
    "IAB573-560" : "Style & Fashion/Women's Fashion/Women's Shoes and Footwear",
    "IAB596" : "Technology & Computing",
    "IAB597-596" : "Technology & Computing/Artificial Intelligence",
    "IAB598-596" : "Technology & Computing/Augmented Reality",
    "IAB599-596" : "Technology & Computing/Computing",
    "IAB600-599" : "Technology & Computing/Computing/Computer Networking",
    "IAB601-599" : "Technology & Computing/Computing/Computer Peripherals",
    "IAB602-599" : "Technology & Computing/Computing/Computer Software and Applications",
    "IAB603-602" : "Technology & Computing/Computing/Computer Software and Applications/3-D Graphics",
    "IAB608-602" : "Technology & Computing/Computing/Computer Software and Applications/Antivirus Software",
    "IAB609-602" : "Technology & Computing/Computing/Computer Software and Applications/Browsers",
    "IAB610-602" : "Technology & Computing/Computing/Computer Software and Applications/Computer Animation",
    "IAB611-602" : "Technology & Computing/Computing/Computer Software and Applications/Databases",
    "IAB612-602" : "Technology & Computing/Computing/Computer Software and Applications/Desktop Publishing",
    "IAB613-602" : "Technology & Computing/Computing/Computer Software and Applications/Digital Audio",
    "IAB614-602" : "Technology & Computing/Computing/Computer Software and Applications/Graphics Software",
    "IAB615-602" : "Technology & Computing/Computing/Computer Software and Applications/Operating Systems",
    "IAB604-602" : "Technology & Computing/Computing/Computer Software and Applications/Photo Editing Software",
    "IAB605-602" : "Technology & Computing/Computing/Computer Software and Applications/Shareware and Freeware",
    "IAB606-602" : "Technology & Computing/Computing/Computer Software and Applications/Video Software",
    "IAB607-602" : "Technology & Computing/Computing/Computer Software and Applications/Web Conferencing",
    "IAB616-599" : "Technology & Computing/Computing/Data Storage and Warehousing",
    "IAB617-599" : "Technology & Computing/Computing/Desktops",
    "IAB618-599" : "Technology & Computing/Computing/Information and Network Security",
    "IAB619-599" : "Technology & Computing/Computing/Internet",
    "IAB620-619" : "Technology & Computing/Computing/Internet/Cloud Computing",
    "IAB623-619" : "Technology & Computing/Computing/Internet/Email",
    "IAB626-619" : "Technology & Computing/Computing/Internet/IT and Internet Support",
    "IAB624-619" : "Technology & Computing/Computing/Internet/Internet for Beginners",
    "IAB625-619" : "Technology & Computing/Computing/Internet/Internet of Things",
    "IAB627-619" : "Technology & Computing/Computing/Internet/Search",
    "IAB628-619" : "Technology & Computing/Computing/Internet/Social Networking",
    "IAB629-619" : "Technology & Computing/Computing/Internet/Web Design and HTML",
    "IAB621-619" : "Technology & Computing/Computing/Internet/Web Development",
    "IAB622-619" : "Technology & Computing/Computing/Internet/Web Hosting",
    "IAB630-599" : "Technology & Computing/Computing/Laptops",
    "IAB631-599" : "Technology & Computing/Computing/Programming Languages",
    "IAB632-596" : "Technology & Computing/Consumer Electronics",
    "IAB633-632" : "Technology & Computing/Consumer Electronics/Cameras and Camcorders",
    "IAB634-632" : "Technology & Computing/Consumer Electronics/Home Entertainment Systems",
    "IAB635-632" : "Technology & Computing/Consumer Electronics/Smartphones",
    "IAB636-632" : "Technology & Computing/Consumer Electronics/Tablets and E-readers",
    "IAB637-632" : "Technology & Computing/Consumer Electronics/Wearable Technology",
    "IAB638-596" : "Technology & Computing/Robotics",
    "IAB639-596" : "Technology & Computing/Virtual Reality",
    "IAB640" : "Television",
    "IAB641-640" : "Television/Animation TV",
    "IAB645-640" : "Television/Children's TV",
    "IAB646-640" : "Television/Comedy TV",
    "IAB647-640" : "Television/Drama TV",
    "IAB648-640" : "Television/Factual TV",
    "IAB649-640" : "Television/Holiday TV",
    "IAB650-640" : "Television/Music TV",
    "IAB651-640" : "Television/Reality TV",
    "IAB652-640" : "Television/Science Fiction TV",
    "IAB642-640" : "Television/Soap Opera TV",
    "IAB643-640" : "Television/Special Interest TV",
    "IAB644-640" : "Television/Sports TV",
    "IAB653" : "Travel",
    "IAB654-653" : "Travel/Travel Accessories",
    "IAB655-653" : "Travel/Travel Locations",
    "IAB656-655" : "Travel/Travel Locations/Africa Travel",
    "IAB657-655" : "Travel/Travel Locations/Asia Travel",
    "IAB658-655" : "Travel/Travel Locations/Australia and Oceania Travel",
    "IAB659-655" : "Travel/Travel Locations/Europe Travel",
    "IAB660-655" : "Travel/Travel Locations/North America Travel",
    "IAB661-655" : "Travel/Travel Locations/Polar Travel",
    "IAB662-655" : "Travel/Travel Locations/South America Travel",
    "IAB663-653" : "Travel/Travel Preparation and Advice",
    "IAB664-653" : "Travel/Travel Type",
    "IAB665-664" : "Travel/Travel Type/Adventure Travel",
    "IAB672-664" : "Travel/Travel Type/Air Travel",
    "IAB673-664" : "Travel/Travel Type/Beach Travel",
    "IAB674-664" : "Travel/Travel Type/Bed & Breakfasts",
    "IAB675-664" : "Travel/Travel Type/Budget Travel",
    "IAB676-664" : "Travel/Travel Type/Business Travel",
    "IAB677-664" : "Travel/Travel Type/Camping",
    "IAB678-664" : "Travel/Travel Type/Cruises",
    "IAB679-664" : "Travel/Travel Type/Day Trips",
    "IAB666-664" : "Travel/Travel Type/Family Travel",
    "IAB667-664" : "Travel/Travel Type/Honeymoons and Getaways",
    "IAB668-664" : "Travel/Travel Type/Hotels and Motels",
    "IAB669-664" : "Travel/Travel Type/Rail Travel",
    "IAB670-664" : "Travel/Travel Type/Road Trips",
    "IAB671-664" : "Travel/Travel Type/Spas",
    "IAB680" : "Video Gaming",
    "IAB681-680" : "Video Gaming/Console Games",
    "IAB683-680" : "Video Gaming/Mobile Games",
    "IAB684-680" : "Video Gaming/PC Games",
    "IAB685-680" : "Video Gaming/Video Game Genres",
    "IAB686-685" : "Video Gaming/Video Game Genres/Action Video Games",
    "IAB691-685" : "Video Gaming/Video Game Genres/Action-Adventure Video Games",
    "IAB692-685" : "Video Gaming/Video Game Genres/Adventure Video Games",
    "IAB693-685" : "Video Gaming/Video Game Genres/Casual Games",
    "IAB694-685" : "Video Gaming/Video Game Genres/Educational Video Games",
    "IAB695-685" : "Video Gaming/Video Game Genres/Exercise and Fitness Video Games",
    "IAB696-685" : "Video Gaming/Video Game Genres/MMOs",
    "IAB697-685" : "Video Gaming/Video Game Genres/Music and Party Video Games",
    "IAB698-685" : "Video Gaming/Video Game Genres/Puzzle Video Games",
    "IAB687-685" : "Video Gaming/Video Game Genres/Role-Playing Video Games",
    "IAB688-685" : "Video Gaming/Video Game Genres/Simulation Video Games",
    "IAB689-685" : "Video Gaming/Video Game Genres/Sports Video Games",
    "IAB690-685" : "Video Gaming/Video Game Genres/Strategy Video Games",
    "IAB682-680" : "Video Gaming/eSports",
}
iab_names2codes_map = { v:k for k,v in iab_codes2names_map.items()}
